spring:
  config:
    activate:
      on-profile:
        - prod
  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
