spring:
  config:
    activate:
      on-profile:
        - local
  jackson:
    property-naming-strategy: SNAKE_CASE

  mongodb:
    embedded:
      version: 4.0.21
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

logging:
  level:
    root: debug